name: travel-mapper
services:
  server:
    image: butlerx/travel-mapper
    build: .
    env_file: .env
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/workspace
  migration:
    image: butlerx/travel-mapper
    build: .
    command: database
    stdin_open: true
    tty: true
    entrypoint:
      - python3
    volumes:
      - .:/workspace
