use wasm_bindgen::prelude::*;

#[must_use]
#[wasm_bindgen]
pub fn carrier_icon_url(carrier: &str, travel_type: &str, size: u32) -> String {
    let fallback = match travel_type {
        "air" => "/static/icons/plane.svg",
        "rail" => "/static/icons/train.svg",
        "boat" => "/static/icons/boat.svg",
        _ => "/static/icons/transport.svg",
    };

    if carrier.is_empty() {
        return format!(
            r#"<img src="{fallback}" alt="{travel_type}" width="{size}" height="{size}" style="vertical-align:middle;border-radius:50%;">"#
        );
    }

    if let Some(domain) = carrier_domain(carrier) {
        let src = format!("https://www.google.com/s2/favicons?domain={domain}&sz=64");
        let escaped = super::geo::escape_html(carrier);
        return format!(
            r#"<img src="{src}" alt="{escaped}" width="{size}" height="{size}" style="vertical-align:middle;border-radius:50%;" onerror="this.onerror=null;this.src='{fallback}';">"#
        );
    }

    format!(
        r#"<img src="{fallback}" alt="{travel_type}" width="{size}" height="{size}" style="vertical-align:middle;border-radius:50%;">"#
    )
}

fn carrier_domain(carrier: &str) -> Option<&'static str> {
    let key = carrier.to_lowercase();
    let key = key.trim();
    match key {
        "aer lingus" => Some("aerlingus.com"),
        "aeroflot" => Some("aeroflot.ru"),
        "air france" => Some("airfrance.com"),
        "air canada" => Some("aircanada.com"),
        "alaska airlines" => Some("alaskaair.com"),
        "american airlines" | "aa" => Some("aa.com"),
        "asiana airlines" | "asiana" => Some("flyasiana.com"),
        "british airways" => Some("britishairways.com"),
        "cathay pacific" => Some("cathaypacific.com"),
        "delta" | "delta air lines" => Some("delta.com"),
        "easyjet" => Some("easyjet.com"),
        "emirates" => Some("emirates.com"),
        "etihad" | "etihad airways" => Some("etihad.com"),
        "finnair" => Some("finnair.com"),
        "iberia" => Some("iberia.com"),
        "ita airways" | "ita" => Some("ita-airways.com"),
        "japan airlines" | "jal" => Some("jal.com"),
        "jetblue" => Some("jetblue.com"),
        "kenmore air" => Some("kenmoreair.com"),
        "klm" => Some("klm.com"),
        "korean air" => Some("koreanair.com"),
        "lufthansa" => Some("lufthansa.com"),
        "norwegian" | "norwegian air" => Some("norwegian.com"),
        "qatar airways" | "qatar" => Some("qatarairways.com"),
        "ryanair" => Some("ryanair.com"),
        "sas" | "scandinavian airlines" => Some("flysas.com"),
        "singapore airlines" => Some("singaporeair.com"),
        "southwest" | "southwest airlines" => Some("southwest.com"),
        "swiss" | "swiss international" => Some("swiss.com"),
        "tap" | "tap portugal" | "tap air portugal" => Some("flytap.com"),
        "turkish airlines" => Some("turkishairlines.com"),
        "united" | "united airlines" => Some("united.com"),
        "virgin atlantic" => Some("virginatlantic.com"),
        "vueling" => Some("vueling.com"),
        "wizz air" | "wizzair" => Some("wizzair.com"),
        "eurostar" => Some("eurostar.com"),
        "thalys" => Some("thalys.com"),
        "sncf" => Some("sncf.com"),
        "trenitalia" => Some("trenitalia.com"),
        "italo" => Some("italotreno.it"),
        "db" | "deutsche bahn" | "intercity express" => Some("bahn.de"),
        "obb" | "öbb" => Some("oebb.at"),
        "sbb" | "cff" | "ffs" => Some("sbb.ch"),
        "ns" | "nederlandse spoorwegen" => Some("ns.nl"),
        "sj" => Some("sj.se"),
        "renfe" => Some("renfe.com"),
        "cp" | "comboios de portugal" => Some("cp.pt"),
        "irish rail" | "iarnród éireann" | "iarnrod eireann" => Some("irishrail.ie"),
        "avanti" | "avanti west coast" => Some("avantiwestcoast.co.uk"),
        "lner" => Some("lner.co.uk"),
        "gwr" | "great western railway" => Some("gwr.com"),
        "scotrail" => Some("scotrail.co.uk"),
        "southeastern" => Some("southeasternrailway.co.uk"),
        "northern" | "northern trains" => Some("northernrailway.co.uk"),
        "crosscountry" => Some("crosscountrytrains.co.uk"),
        "transpennine" | "transpennine express" => Some("tpexpress.co.uk"),
        "east midlands railway" | "emr" => Some("eastmidlandsrailway.co.uk"),
        "amtrak" => Some("amtrak.com"),
        "via rail" | "via" => Some("viarail.ca"),
        "korail" => Some("letskorail.com"),
        "jr" | "japan rail" => Some("jrpass.com"),
        "dart" => Some("irishrail.ie"),
        "regiojet" | "regiojet train" => Some("regiojet.com"),
        "glacier express" => Some("glacierexpress.ch"),
        "stena line" | "stena" => Some("stenaline.com"),
        "irish ferries" => Some("irishferries.com"),
        "brittany ferries" => Some("brittany-ferries.co.uk"),
        "p&o ferries" | "p&o" => Some("poferries.com"),
        "dfds" => Some("dfds.com"),
        "viking line" => Some("vikingline.com"),
        "tallink" | "tallink silja" => Some("tallink.com"),
        "color line" => Some("colorline.com"),
        "fjord line" => Some("fjordline.com"),
        "corsica ferries" => Some("corsica-ferries.co.uk"),
        "moby" | "moby lines" => Some("moby.it"),
        "tirrenia" => Some("tirrenia.it"),
        "grimaldi lines" | "grimaldi" => Some("grimaldi-lines.com"),
        "condor ferries" | "condor" => Some("condorferries.co.uk"),
        "wightlink" => Some("wightlink.co.uk"),
        "caledonian macbrayne" | "calmac" => Some("calmac.co.uk"),
        "flixbus" | "flix" => Some("flixbus.com"),
        "greyhound" => Some("greyhound.com"),
        "national express" => Some("nationalexpress.com"),
        "megabus" => Some("megabus.com"),
        "bus eireann" | "bus éireann" => Some("buseireann.ie"),
        "eurolines" => Some("eurolines.eu"),
        "ouigo" => Some("ouigo.com"),
        _ => None,
    }
}

#[must_use]
#[wasm_bindgen]
pub fn country_alpha2(numeric_id: &str) -> String {
    match numeric_id {
        "004" => "AF",
        "008" => "AL",
        "010" => "AQ",
        "012" => "DZ",
        "016" => "AS",
        "020" => "AD",
        "024" => "AO",
        "028" => "AG",
        "031" => "AZ",
        "032" => "AR",
        "036" => "AU",
        "040" => "AT",
        "044" => "BS",
        "048" => "BH",
        "050" => "BD",
        "051" => "AM",
        "052" => "BB",
        "056" => "BE",
        "060" => "BM",
        "064" => "BT",
        "068" => "BO",
        "070" => "BA",
        "072" => "BW",
        "076" => "BR",
        "084" => "BZ",
        "090" => "SB",
        "096" => "BN",
        "100" => "BG",
        "104" => "MM",
        "108" => "BI",
        "112" => "BY",
        "116" => "KH",
        "120" => "CM",
        "124" => "CA",
        "132" => "CV",
        "140" => "CF",
        "144" => "LK",
        "148" => "TD",
        "152" => "CL",
        "156" => "CN",
        "158" => "TW",
        "170" => "CO",
        "174" => "KM",
        "175" => "YT",
        "178" => "CG",
        "180" => "CD",
        "184" => "CK",
        "188" => "CR",
        "191" => "HR",
        "192" => "CU",
        "196" => "CY",
        "203" => "CZ",
        "204" => "BJ",
        "208" => "DK",
        "212" => "DM",
        "214" => "DO",
        "218" => "EC",
        "222" => "SV",
        "226" => "GQ",
        "231" => "ET",
        "232" => "ER",
        "233" => "EE",
        "234" => "FO",
        "238" => "FK",
        "242" => "FJ",
        "246" => "FI",
        "250" => "FR",
        "254" => "GF",
        "258" => "PF",
        "260" => "TF",
        "262" => "DJ",
        "266" => "GA",
        "268" => "GE",
        "270" => "GM",
        "275" => "PS",
        "276" => "DE",
        "288" => "GH",
        "292" => "GI",
        "296" => "KI",
        "300" => "GR",
        "304" => "GL",
        "308" => "GD",
        "312" => "GP",
        "316" => "GU",
        "320" => "GT",
        "324" => "GN",
        "328" => "GY",
        "332" => "HT",
        "336" => "VA",
        "340" => "HN",
        "344" => "HK",
        "348" => "HU",
        "352" => "IS",
        "356" => "IN",
        "360" => "ID",
        "364" => "IR",
        "368" => "IQ",
        "372" => "IE",
        "376" => "IL",
        "380" => "IT",
        "384" => "CI",
        "388" => "JM",
        "392" => "JP",
        "398" => "KZ",
        "400" => "JO",
        "404" => "KE",
        "408" => "KP",
        "410" => "KR",
        "414" => "KW",
        "417" => "KG",
        "418" => "LA",
        "422" => "LB",
        "426" => "LS",
        "428" => "LV",
        "430" => "LR",
        "434" => "LY",
        "438" => "LI",
        "440" => "LT",
        "442" => "LU",
        "446" => "MO",
        "450" => "MG",
        "454" => "MW",
        "458" => "MY",
        "462" => "MV",
        "466" => "ML",
        "470" => "MT",
        "474" => "MQ",
        "478" => "MR",
        "480" => "MU",
        "484" => "MX",
        "492" => "MC",
        "496" => "MN",
        "498" => "MD",
        "499" => "ME",
        "504" => "MA",
        "508" => "MZ",
        "512" => "OM",
        "516" => "NA",
        "520" => "NR",
        "524" => "NP",
        "528" => "NL",
        "530" => "AN",
        "533" => "AW",
        "540" => "NC",
        "548" => "VU",
        "554" => "NZ",
        "558" => "NI",
        "562" => "NE",
        "566" => "NG",
        "570" => "NU",
        "574" => "NF",
        "578" => "NO",
        "580" => "MP",
        "583" => "FM",
        "584" => "MH",
        "585" => "PW",
        "586" => "PK",
        "591" => "PA",
        "598" => "PG",
        "600" => "PY",
        "604" => "PE",
        "608" => "PH",
        "612" => "PN",
        "616" => "PL",
        "620" => "PT",
        "624" => "GW",
        "626" => "TL",
        "630" => "PR",
        "634" => "QA",
        "638" => "RE",
        "642" => "RO",
        "643" => "RU",
        "646" => "RW",
        "654" => "SH",
        "659" => "KN",
        "660" => "AI",
        "662" => "LC",
        "666" => "PM",
        "670" => "VC",
        "674" => "SM",
        "678" => "ST",
        "682" => "SA",
        "686" => "SN",
        "688" => "RS",
        "690" => "SC",
        "694" => "SL",
        "702" => "SG",
        "703" => "SK",
        "704" => "VN",
        "705" => "SI",
        "706" => "SO",
        "710" => "ZA",
        "716" => "ZW",
        "720" | "887" => "YE",
        "724" => "ES",
        "732" => "EH",
        "736" => "SD",
        "740" => "SR",
        "744" => "SJ",
        "748" => "SZ",
        "752" => "SE",
        "756" => "CH",
        "760" => "SY",
        "762" => "TJ",
        "764" => "TH",
        "768" => "TG",
        "772" => "TK",
        "776" => "TO",
        "780" => "TT",
        "784" => "AE",
        "788" => "TN",
        "792" => "TR",
        "795" => "TM",
        "796" => "TC",
        "798" => "TV",
        "800" => "UG",
        "804" => "UA",
        "807" => "MK",
        "818" => "EG",
        "826" => "GB",
        "834" => "TZ",
        "840" => "US",
        "854" => "BF",
        "858" => "UY",
        "860" => "UZ",
        "862" => "VE",
        "876" => "WF",
        "882" => "WS",
        "894" => "ZM",
        "-99" => "CY",
        "900" => "XK",
        _ => "",
    }
    .to_owned()
}

#[must_use]
#[wasm_bindgen]
pub fn visit_color(count: u32) -> String {
    match count {
        50.. => "#fde724",
        25..=49 => "#6ece58",
        15..=24 => "#1f9e89",
        10..=14 => "#26828e",
        5..=9 => "#31688e",
        3..=4 => "#3e4989",
        2 => "#482878",
        1 => "#473677",
        0 => "transparent",
    }
    .to_owned()
}
